Repository senaite/senaite.app.listing, pull requests merged in 2019-02, with the labels that each got.

#2 Support for subscriber adapters
  .gitignore
  README.md
  src/senaite/core/listing/ajax.py
  src/senaite/core/listing/interfaces.py
  src/senaite/core/listing/utils.py
  src/senaite/core/listing/view.py
Labels: enhancement

#3 Ensure subscriber adapters for ListingView are called at the end
  src/senaite/core/listing/interfaces.py
  src/senaite/core/listing/view.py
Labels: P1: Urgent

#4 Make priority_order optional and set 1000 as default
  src/senaite/core/listing/interfaces.py
  src/senaite/core/listing/view.py
Labels: P1: Urgent

#5 Detection Limit handling in the Frontend/Backend
  docs/Changelog.rst
  setup.py
  src/senaite/core/listing/react/components/NumericField.coffee
  src/senaite/core/listing/react/components/Select.coffee
  src/senaite/core/listing/static/js/senaite.core.listing.js
Labels: Bug, Cleanup, P0: Critical
