Repository senaite/senaite.app.listing, pull requests merged in 2023-10, with the labels that each got.

#122 Add context menu for item transitions
  docs/Changelog.rst
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.css
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.js
  webpack/app/components/ButtonBar.coffee
  webpack/app/components/Constants.js
  webpack/app/components/ContextMenu.js
  webpack/app/components/TableCells.coffee
  webpack/app/components/TableHeaderRow.coffee
  webpack/app/components/TableRow.js
  webpack/app/listing.coffee
  webpack/package.json
  webpack/yarn.lock
Labels: Addition, Enhancement

#123 Move logic to calculate possible listing transitions for selected UIDs into an own adapter
  docs/Changelog.rst
  src/senaite/app/listing/adapters/configure.zcml
  src/senaite/app/listing/adapters/transitions.py
  src/senaite/app/listing/ajax.py
  src/senaite/app/listing/interfaces.py
Labels: Enhancement

#128 Fix translation strings
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.js
  webpack/app/components/TableColumnConfig.coffee
  webpack/app/listing.coffee
Labels: Bug

#129 Fix progress bar not always showing
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.js
  webpack/app/listing.coffee
Labels: Bug

#131 Added FractionField for fraction-like results support
  docs/Changelog.rst
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.js
  webpack/app/components/FractionField.coffee
  webpack/app/components/TableCell.coffee
Labels: Enhancement

#132 Improve transposed interims formatting
  docs/Changelog.rst
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.js
  webpack/app/components/TableTransposedCell.coffee
Labels: Enhancement
