Repository senaite/senaite.app.listing, pull requests merged in 2023-09, with the labels that each got.

#110 Sequential save action
  docs/Changelog.rst
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.js
  webpack/app/components/TableCells.coffee
  webpack/app/listing.coffee
Labels: Enhancement

#112 Handle transition fails without UI notification
  docs/Changelog.rst
  src/senaite/app/listing/ajax.py
Labels: Enhancement

#113 Enable ajax transitions per default
  docs/Changelog.rst
  src/senaite/app/listing/controlpanel.py
Labels: Enhancement

#115 Support redirects after Ajax transitions
  docs/Changelog.rst
  src/senaite/app/listing/adapters/configure.zcml
  src/senaite/app/listing/adapters/workflow.py
  src/senaite/app/listing/ajax.py
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.js
  src/senaite/app/listing/interfaces.py
  webpack/app/api.coffee
  webpack/app/listing.coffee
Labels: Addition

#117 Compatibility with senaite.core i18n
  docs/Changelog.rst
  src/senaite/app/listing/decorators.py
Labels: Cleanup

#120 Auto-add dependents after listing transition
  docs/Changelog.rst
  src/senaite/app/listing/adapters/workflow.py
  src/senaite/app/listing/ajax.py
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.js
  webpack/app/listing.coffee
Labels: Enhancement

#121 Trigger event after sequential transitions
  docs/Changelog.rst
  src/senaite/app/listing/browser/static/bundles/senaite.app.listing.js
  webpack/app/listing.coffee
Labels: Cleanup, Enhancement
